### ISSUE TITLE
中文输入法与文件路径问题

### ISSUE THREAD

**Issue by Drunghao** [RokasUrbelis/docker-wine-linux#1]
deepin下载了企业微信deb包，单独构建镜像
构建后用docker exec -ti xxx /usr/bin/nohup /bin/bash &>/dev/null WXWork &打开
界面正常，收发消息正常
但无法启用中文输入法，以及找不到主机文件目录，所以收发文件也是个问题

**Comment by RokasUrbelis** [comment]
可以问下deepin开发团队，只要宿主机输入法正常，一般都是可以正常切换输入法的。主机文件目录在容器.deepin_wine下面

**Comment by yenanfei** [comment]
同企业微信用户，无法使用中文输入法

**Comment by RokasUrbelis** [comment]
> deepin下载了企业微信deb包，单独构建镜像
> 构建后用docker exec -ti xxx /usr/bin/nohup /bin/bash &>/dev/null WXWork &打开
> 界面正常，收发消息正常
> 但无法启用中文输入法，以及找不到主机文件目录，所以收发文件也是个问题
可以问下deepin开发团队，这个包我没有试过，所以不敢妄下结论，只要宿主机输入法正常，一般都是可以正常切换输入法的。主机文件目录在容器的~/.deepin_wine下面

**Comment by RokasUrbelis** [comment]
> 同企业微信用户，无法使用中文输入法

镜像用的是Ubuntu，企业微信是deepin团队开发的包，能不能在上面运行我没有测试过，用了其它包出现不兼容或者运行不了都是意料之中的

**Comment by ghost** [comment]
> deepin下载了企业微信deb包，单独构建镜像
> 构建后用docker exec -ti xxx /usr/bin/nohup /bin/bash &>/dev/null WXWork &打开
> 界面正常，收发消息正常
> 但无法启用中文输入法，以及找不到主机文件目录，所以收发文件也是个问题

可以问下deepin开发团队，这个包我没有试过，所以不敢妄下结论，只要宿主机输入法正常，一般都是可以正常切换输入法的。主机文件目录在容器的~/.deepin_wine下面

**Comment by ghost** [comment]
> 同企业微信用户，无法使用中文输入法

镜像用的是Ubuntu，企业微信是deepin团队开发的包，能不能在上面运行我没有测试过，只测试了我说的那几个应用是正常的，用了其它包出现不兼容或者运行不了都是意料之中的，不建议使用，除非有需求

**Comment by Drunghao** [comment]
> 可以问下deepin开发团队，这个包我没有试过，所以不敢妄下结论，只要宿主机输入法正常，一般都是可以正常切换输入法的。主机文件目录在容器的~/.deepin_wine下面

那么是docker run要挂载个共享文件夹，再软链~/.deepin_wine吗？

**Comment by ghost** [comment]
> > 可以问下deepin开发团队，这个包我没有试过，所以不敢妄下结论，只要宿主机输入法正常，一般都是可以正常切换输入法的。主机文件目录在容器的~/.deepin_wine下面
> 
> 那么是docker run要挂载个共享文件夹，再软链~/.deepin_wine吗？

README已更新，具体请看[这里](https://github.com/RokasUrbelis/docker-wine-linux#1card_file_box%E5%BA%94%E7%94%A8%E4%BD%BF%E7%94%A8%E8%BF%87%E7%A8%8B%E6%96%87%E4%BB%B6%E4%BC%A0%E8%BE%93%E7%9A%84%E8%B7%AF%E5%BE%84%E9%97%AE%E9%A2%98)
