### ISSUE TITLE
KDE error

### ISSUE THREAD

**Issue by Tsingv** [RokasUrbelis/docker-wine-linux#12]
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  10
  Current serial number in output stream:  10

Above, I have no idea what happend, 'xarclock' can be run and display on my desktop.

**Comment by Tsingv** [comment]
https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12

perfect

**Comment by RokasUrbelis** [comment]
> X Error of failed request: BadWindow (invalid Window parameter)
> Major opcode of failed request: 20 (X_GetProperty)
> Resource id in failed request: 0x0
> Serial number of failed request: 10
> Current serial number in output stream: 10
> 
> Above, I have no idea what happend, 'xarclock' can be run and display on my desktop.

enter the docker container and exec "apt install gnome-settings-daemon",then exec " /usr/lib/gnome-settings-daemon/gsd-xsettings &" or "gnome-settings-daemon &"
thanks report
