### ISSUE TITLE
完美安装、完美运行，就是没有声音

### ISSUE THREAD

**Issue by Cloud300** [RokasUrbelis/docker-wine-linux#14]
语音听不了，播放视频也没有声音。是我的问题吗？可不可以解决呢？？

**Comment by RokasUrbelis** [comment]
目前docker容器技术做不到驱动映射，因此无法解决该问题

> 语音听不了，播放视频也没有声音。是我的问题吗？可不可以解决呢？？

**Comment by gorquan** [comment]
可以尝试一下alsa和Pulseaudio [https://askubuntu.com/questions/972510/how-to-set-alsa-default-device-to-pulseaudio-sound-server-on-docker](url)

**Comment by gorquan** [comment]
我本人封装了一个支持声音输出的wine docker，感兴趣可以去看看
https://github.com/gorquan/deepin-wine-docker
