### ISSUE TITLE
tim/qq底下聊天框无法正常显示汉字

### ISSUE THREAD

**Issue by chinoll** [RokasUrbelis/docker-wine-linux#15]
系统：archlinux
内核版本号：5.2.3-arch1-1-ARCH
桌面环境：DDE(deepin)
Docker version 19.03.1-ce, build 74b1e89e8a
qq/tim底下聊天框汉字显示口字,

**Comment by RokasUrbelis** [comment]
[#145](https://github.com/askme765cs/Wine-QQ-TIM/issues/145)

**Comment by RokasUrbelis** [comment]
> 系统：archlinux
> 内核版本号：5.2.3-arch1-1-ARCH
> 桌面环境：DDE(deepin)
> Docker version 19.03.1-ce, build 74b1e89e8a
> qq/tim底下聊天框汉字显示口字,

[#145](https://github.com/askme765cs/Wine-QQ-TIM/issues/145)

**Comment by iPixelOldC** [comment]
额(°_°)…那个，Deepin直接去商店安装不就行了.....不用搞这货吧，毕竟这货的资源都是从Deepin来的......
