### ISSUE TITLE
运行bash run.sh出错

### ISSUE THREAD

**Issue by wanghao19951021** [RokasUrbelis/docker-wine-linux#2]
最终提示如下信息：

E: 无法下载 http://archive.ubuntu.com/ubuntu/pool/main/m/mpfr4/libmpfr6_4.0.1-1_i386.deb  连接失败 [IP: 91.189.88.162 80]
E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？
The command '/bin/sh -c yes|bash /root/deepin-wine-ubuntu/install.sh' returned a non-zero code: 100
Unable to find image 'docker-wine-linux:latest' locally
docker: Error response from daemon: pull access denied for docker-wine-linux, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Your container id is 
[+]Run [source start.sh -i   TIM] to run TIM or another APP

**Comment by RokasUrbelis** [comment]
bug已修复，请执行uninstall.sh卸载，之后重新git clone此项目

**Comment by RokasUrbelis** [comment]
> 最终提示如下信息：
> 
> E: 无法下载 http://archive.ubuntu.com/ubuntu/pool/main/m/mpfr4/libmpfr6_4.0.1-1_i386.deb 连接失败 [IP: 91.189.88.162 80]
> E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？
> The command '/bin/sh -c yes|bash /root/deepin-wine-ubuntu/install.sh' returned a non-zero code: 100
> Unable to find image 'docker-wine-linux:latest' locally
> docker: Error response from daemon: pull access denied for docker-wine-linux, repository does not exist or may require 'docker login'.
> See 'docker run --help'.
> Your container id is
> [+]Run [source start.sh -i TIM] to run TIM or another APP

bug已修复，请执行uninstall.sh卸载，之后重新git clone此项目
