### ISSUE TITLE
百度云盘可以移除了呀，有官方的linux

### ISSUE THREAD

**Issue by ijkzen** [RokasUrbelis/docker-wine-linux#23]
https://pan.baidu.com/download

**Comment by RokasUrbelis** [comment]
> https://pan.baidu.com/download

官方发行版有bug，并不是针对所有发行版发行，且有些发行版运行异常

**Comment by ijkzen** [comment]
官方发行版有bug，并不是针对所有发行版发行，且有些发行版运行异常
