### ISSUE TITLE
WeChat打不开了

### ISSUE THREAD

**Issue by Cloud300** [RokasUrbelis/docker-wine-linux#24]
首先感谢楼主
现在每次打开WeChat都会有提示更新的窗口，关掉后扫码登录，会一直卡在：正在登录界面进不去
希望楼主费心解决此问题
非常感谢

**Comment by RokasUrbelis** [comment]
> 首先感谢楼主
> 现在每次打开WeChat都会有提示更新的窗口，关掉后扫码登录，会一直卡在：正在登录界面进不去
> 希望楼主费心解决此问题
> 非常感谢

请提供下wechat提示更新的窗口截图、docker version输出信息以及系统发行版、内核版本以及桌面环境

**Comment by Cloud300** [comment]
就像图片中显示的一样，我可以把更新到最新版本的窗口关掉。但是登录界面一直是在正在登录...

系统信息：
Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU
桌面环境：
gnome
Docker版本：
root@kali:~/docker-wine-linux# docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 23 Jun 2019 01:25:10 +0800
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Sat Jun 22 17:25:10 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by Cloud300** [comment]
![2019-08-27 17-53-54 的屏幕截图](https://user-images.githubusercontent.com/39040440/63735140-63c2fb00-c8b1-11e9-9eb3-ee1648a716e9.png)

**Comment by RokasUrbelis** [comment]
> 就像图片中显示的一样，我可以把更新到最新版本的窗口关掉。但是登录界面一直是在正在登录...
> 
> 系统信息：
> Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU
> 桌面环境：
> gnome
> Docker版本：
> root@kali:~/docker-wine-linux# docker version
> Client:
> Version: 18.09.1
> API version: 1.39
> Go version: go1.11.6
> Git commit: 4c52b90
> Built: Sun, 23 Jun 2019 01:25:10 +0800
> OS/Arch: linux/amd64
> Experimental: false
> 
> Server:
> Engine:
> Version: 18.09.1
> API version: 1.39 (minimum version 1.12)
> Go version: go1.11.6
> Git commit: 4c52b90
> Built: Sat Jun 22 17:25:10 2019
> OS/Arch: linux/amd64
> Experimental: false

微信版本已更新，可重新拉取此项目

**Comment by Cloud300** [comment]
楼主你好，感谢你能关注我的回复
我本人是一个小白，我想问一下你说的重新拉取这个项目：
需要将原先的项目删除掉，还是直接重新拉取覆盖？？
如果要删除干净我应该怎么做，感觉这跟卸载软件不太一样
麻烦您帮我一下☺

**Comment by RokasUrbelis** [comment]
> 楼主你好，感谢你能关注我的回复
> 我本人是一个小白，我想问一下你说的重新拉取这个项目：
> 需要将原先的项目删除掉，还是直接重新拉取覆盖？？
> 如果要删除干净我应该怎么做，感觉这跟卸载软件不太一样
> 麻烦您帮我一下☺

执行`bash uninstall.sh`卸载后，在旧项目路径执行`git pull https://github.com/RokasUrbelis/docker-wine-linux`即可
