### ISSUE TITLE
自己添加第三方钉钉的安装包，但是start的时候，如何指定APP NAME？

### ISSUE THREAD

**Issue by chenshuai1995** [RokasUrbelis/docker-wine-linux#29]
我先把安装包放入到了deb目录下面，然后执行run.sh，之后start的时候不知道如何指定APP NAME？

**Comment by chenshuai1995** [comment]
@RokasUrbelis

**Comment by RokasUrbelis** [comment]
应用名通常为安装包的名字(去除版本号等等)，即dingtalk，但wine暂不支持钉钉，故安装上去可能无法正常使用
