### ISSUE TITLE
运行bash start.sh -i 018a1ccda4aa TIM后没有反应

### ISSUE THREAD

**Issue by COOLMSF** [RokasUrbelis/docker-wine-linux#35]
运行环境 : Manjaro i3, 5.4.18-1-MANJARO
docker version : Docker version 19.03.5-ce, build 633a0ea838
运行docker logs 018a1ccda4aa(id of docker-wine-linux)后什么都不显示。
请问怎么解决。

**Comment by amtoaer** [comment]
我`Manjaro xfce`也无显示，我觉得可能像#3 说的一样，不支持当前桌面环境。

**Comment by xch33** [comment]
> 我`Manjaro xfce`也无显示，我觉得可能像#3 说的一样，不支持当前桌面环境。

我也一样
