### ISSUE TITLE
run.sh执行到第七步出错

### ISSUE THREAD

**Issue by wangzl1163** [RokasUrbelis/docker-wine-linux#42]
fedora 32系统，执行bash run.sh到第七步报错。报错信息如下。
`Step 7/16 : RUN apt-get update
 ---> Running in 1bc0895ecc49
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Removing intermediate container 1bc0895ecc49
 ---> d6d3a7f890c6
Step 8/16 : RUN apt-get install wget git locales ttf-wqy-zenhei sudo -y
 ---> Running in bdd183bc7129
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package wget
E: Unable to locate package git
E: Package 'locales' has no installation candidate
E: Unable to locate package ttf-wqy-zenhei
E: Unable to locate package sudo
The command '/bin/sh -c apt-get install wget git locales ttf-wqy-zenhei sudo -y' returned a non-zero code: 100
build docker image error,exit process
`

**Comment by RokasUrbelis** [comment]
> fedora 32系统，执行bash run.sh到第七步报错。报错信息如下。
> `Step 7/16 : RUN apt-get update
> ---> Running in 1bc0895ecc49
> Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
> Temporary failure resolving 'archive.ubuntu.com'
> Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
> Temporary failure resolving 'security.ubuntu.com'
> Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
> Temporary failure resolving 'archive.ubuntu.com'
> Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
> Temporary failure resolving 'archive.ubuntu.com'
> Reading package lists...
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease Temporary failure resolving 'security.ubuntu.com'
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> Removing intermediate container 1bc0895ecc49
> ---> d6d3a7f890c6
> Step 8/16 : RUN apt-get install wget git locales ttf-wqy-zenhei sudo -y
> ---> Running in bdd183bc7129
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package locales is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Unable to locate package wget
> E: Unable to locate package git
> E: Package 'locales' has no installation candidate
> E: Unable to locate package ttf-wqy-zenhei
> E: Unable to locate package sudo
> The command '/bin/sh -c apt-get install wget git locales ttf-wqy-zenhei sudo -y' returned a non-zero code: 100
> build docker image error,exit process
> `

将Dockerfile第十一行替换成国内可用ubuntu源，之后再执行run.sh
