### ISSUE TITLE
run.sh卡在地域选择模块

### ISSUE THREAD

**Issue by WenkaiChen** [RokasUrbelis/docker-wine-linux#43]
Geographic area这个地方输入6之后回车，几小时没有反应。

系统版本ubuntu 16.04.

希望得到开发者反馈～～谢谢

**Comment by JimmyYanDev** [comment]
我遇到了同样的问题

**Comment by JimmyYanDev** [comment]
Duplicate of #40
[解决方案----》](https://github.com/RokasUrbelis/docker-wine-linux/issues/40#issuecomment-620981451)
