### ISSUE TITLE
Faied to run 'bash run.sh'.

### ISSUE THREAD

**Issue by hongyi-zhao** [RokasUrbelis/docker-wine-linux#45]
Hi,

I try to build the docker image for this project, but failed. See the following for more detailed info.

```
$ bash run.sh
[+]Cloning speed may be slow, please waitting...
Cloning into 'deepin-wine-ubuntu'...
remote: Enumerating objects: 3036, done.
remote: Total 3036 (delta 0), reused 0 (delta 0), pack-reused 3036
Receiving objects: 100% (3036/3036), 67.06 MiB | 7.54 MiB/s, done.
Resolving deltas: 100% (1433/1433), done.
Sending build context to Docker daemon  1.235GB
Step 1/16 : FROM ubuntu:latest
 ---> d70eaf7277ea
Step 2/16 : MAINTAINER RokasUrbelis(Based on github deepin-wine-ubuntu project)
 ---> Using cache
 ---> 0deb62e3ee11
Step 3/16 : ADD deepin-wine-ubuntu /root/deepin-wine-ubuntu
 ---> 22647c08b06b
Step 4/16 : COPY link.sh /root/
 ---> f41887ff0be9
Step 5/16 : COPY deb/ /root/deepin-wine-ubuntu/
 ---> 72562dc1f4f7
Step 6/16 : RUN rm -rf /var/lib/apt/lists/*
 ---> Running in fe232a191b35
Removing intermediate container fe232a191b35
 ---> de4f22320035
Step 7/16 : RUN apt-get update
 ---> Running in b399e796ae90
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Removing intermediate container b399e796ae90
 ---> 383c5689dedf
Step 8/16 : RUN apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y
 ---> Running in d90e863d0088
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package wget
E: Unable to locate package git
E: Package 'locales' has no installation candidate
E: Unable to locate package ttf-wqy-zenhei
E: Unable to locate package sudo
E: Unable to locate package tzdata
The command '/bin/sh -c apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y' returned a non-zero code: 100
build docker image error,exit process
```

Any hints for this problem will be highly appreciated.

Regards,
HY

**Comment by RokasUrbelis** [comment]
> Hi,
> 
> I try to build the docker image for this project, but failed. See the following for more detailed info.
> 
> ```
> $ bash run.sh
> [+]Cloning speed may be slow, please waitting...
> Cloning into 'deepin-wine-ubuntu'...
> remote: Enumerating objects: 3036, done.
> remote: Total 3036 (delta 0), reused 0 (delta 0), pack-reused 3036
> Receiving objects: 100% (3036/3036), 67.06 MiB | 7.54 MiB/s, done.
> Resolving deltas: 100% (1433/1433), done.
> Sending build context to Docker daemon  1.235GB
> Step 1/16 : FROM ubuntu:latest
>  ---> d70eaf7277ea
> Step 2/16 : MAINTAINER RokasUrbelis(Based on github deepin-wine-ubuntu project)
>  ---> Using cache
>  ---> 0deb62e3ee11
> Step 3/16 : ADD deepin-wine-ubuntu /root/deepin-wine-ubuntu
>  ---> 22647c08b06b
> Step 4/16 : COPY link.sh /root/
>  ---> f41887ff0be9
> Step 5/16 : COPY deb/ /root/deepin-wine-ubuntu/
>  ---> 72562dc1f4f7
> Step 6/16 : RUN rm -rf /var/lib/apt/lists/*
>  ---> Running in fe232a191b35
> Removing intermediate container fe232a191b35
>  ---> de4f22320035
> Step 7/16 : RUN apt-get update
>  ---> Running in b399e796ae90
> Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
>   Temporary failure resolving 'security.ubuntu.com'
> Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
>   Temporary failure resolving 'archive.ubuntu.com'
> Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
>   Temporary failure resolving 'archive.ubuntu.com'
> Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
>   Temporary failure resolving 'archive.ubuntu.com'
> Reading package lists...
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> Removing intermediate container b399e796ae90
>  ---> 383c5689dedf
> Step 8/16 : RUN apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y
>  ---> Running in d90e863d0088
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package locales is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Unable to locate package wget
> E: Unable to locate package git
> E: Package 'locales' has no installation candidate
> E: Unable to locate package ttf-wqy-zenhei
> E: Unable to locate package sudo
> E: Unable to locate package tzdata
> The command '/bin/sh -c apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y' returned a non-zero code: 100
> build docker image error,exit process
> ```
> 
> Any hints for this problem will be highly appreciated.
> 
> Regards,
> HY

Try exec sed -i '11s/#(.*)/\1/' Dockerfile && bash run.sh

**Comment by hongyi-zhao** [comment]
> Try exec sed -i '11s/#(.*)/\1/' Dockerfile && bash run.sh

You should have said as following:
`
$ sed -ri '11s/#(.*)/\1/' Dockerfile`

But the problem can't be solved by this workaround:

```
$ git diff
diff --git a/Dockerfile b/Dockerfile
index 35a47cc..c552a3e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -8,7 +8,7 @@ MAINTAINER RokasUrbelis(Based on github deepin-wine-ubuntu project)
 ADD deepin-wine-ubuntu /root/deepin-wine-ubuntu
 COPY link.sh /root/
 COPY deb/ /root/deepin-wine-ubuntu/
-#COPY sources.list /etc/apt/
+COPY sources.list /etc/apt/
 RUN rm -rf /var/lib/apt/lists/*
 RUN apt-get update

$  bash run.sh
[+]Cloning speed may be slow, please waitting...
Cloning into 'deepin-wine-ubuntu'...
remote: Enumerating objects: 3036, done.
remote: Total 3036 (delta 0), reused 0 (delta 0), pack-reused 3036
Receiving objects: 100% (3036/3036), 67.06 MiB | 646.00 KiB/s, done.
Resolving deltas: 100% (1433/1433), done.
Sending build context to Docker daemon  1.235GB
Step 1/17 : FROM ubuntu:latest
 ---> d70eaf7277ea
Step 2/17 : MAINTAINER RokasUrbelis(Based on github deepin-wine-ubuntu project)
 ---> Using cache
 ---> 0deb62e3ee11
Step 3/17 : ADD deepin-wine-ubuntu /root/deepin-wine-ubuntu
 ---> db62c0b27aaa
Step 4/17 : COPY link.sh /root/
 ---> 4759f741e5be
Step 5/17 : COPY deb/ /root/deepin-wine-ubuntu/
 ---> 7ae989b80dbc
Step 6/17 : COPY sources.list /etc/apt/
 ---> db086570b913
Step 7/17 : RUN rm -rf /var/lib/apt/lists/*
 ---> Running in 28d99704542a
Removing intermediate container 28d99704542a
 ---> 7a71ed010ece
Step 8/17 : RUN apt-get update
 ---> Running in 1e5da74dd0cd
Err:1 http://mirrors.aliyun.com/ubuntu bionic InRelease
  Temporary failure resolving 'mirrors.aliyun.com'
Err:2 http://mirrors.aliyun.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'mirrors.aliyun.com'
Err:3 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'mirrors.aliyun.com'
Err:4 http://mirrors.aliyun.com/ubuntu bionic-proposed InRelease
  Temporary failure resolving 'mirrors.aliyun.com'
Err:5 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'mirrors.aliyun.com'
Reading package lists...
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-proposed/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Removing intermediate container 1e5da74dd0cd
 ---> 52c618edfb13
Step 9/17 : RUN apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y
 ---> Running in c9aa9920a38f
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package wget
E: Unable to locate package git
E: Package 'locales' has no installation candidate
E: Unable to locate package ttf-wqy-zenhei
E: Unable to locate package sudo
E: Unable to locate package tzdata
The command '/bin/sh -c apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y' returned a non-zero code: 100
build docker image error,exit process

```

**Comment by RokasUrbelis** [comment]
> > Try exec sed -i '11s/#(.*)/\1/' Dockerfile && bash run.sh
> 
> You should have said as following:
> ` $ sed -ri '11s/#(.*)/\1/' Dockerfile`
> 
> But the problem can't be solved by this workaround:
> 
> ```
> $ git diff
> diff --git a/Dockerfile b/Dockerfile
> index 35a47cc..c552a3e 100644
> --- a/Dockerfile
> +++ b/Dockerfile
> @@ -8,7 +8,7 @@ MAINTAINER RokasUrbelis(Based on github deepin-wine-ubuntu project)
>  ADD deepin-wine-ubuntu /root/deepin-wine-ubuntu
>  COPY link.sh /root/
>  COPY deb/ /root/deepin-wine-ubuntu/
> -#COPY sources.list /etc/apt/
> +COPY sources.list /etc/apt/
>  RUN rm -rf /var/lib/apt/lists/*
>  RUN apt-get update
> 
> $  bash run.sh
> [+]Cloning speed may be slow, please waitting...
> Cloning into 'deepin-wine-ubuntu'...
> remote: Enumerating objects: 3036, done.
> remote: Total 3036 (delta 0), reused 0 (delta 0), pack-reused 3036
> Receiving objects: 100% (3036/3036), 67.06 MiB | 646.00 KiB/s, done.
> Resolving deltas: 100% (1433/1433), done.
> Sending build context to Docker daemon  1.235GB
> Step 1/17 : FROM ubuntu:latest
>  ---> d70eaf7277ea
> Step 2/17 : MAINTAINER RokasUrbelis(Based on github deepin-wine-ubuntu project)
>  ---> Using cache
>  ---> 0deb62e3ee11
> Step 3/17 : ADD deepin-wine-ubuntu /root/deepin-wine-ubuntu
>  ---> db62c0b27aaa
> Step 4/17 : COPY link.sh /root/
>  ---> 4759f741e5be
> Step 5/17 : COPY deb/ /root/deepin-wine-ubuntu/
>  ---> 7ae989b80dbc
> Step 6/17 : COPY sources.list /etc/apt/
>  ---> db086570b913
> Step 7/17 : RUN rm -rf /var/lib/apt/lists/*
>  ---> Running in 28d99704542a
> Removing intermediate container 28d99704542a
>  ---> 7a71ed010ece
> Step 8/17 : RUN apt-get update
>  ---> Running in 1e5da74dd0cd
> Err:1 http://mirrors.aliyun.com/ubuntu bionic InRelease
>   Temporary failure resolving 'mirrors.aliyun.com'
> Err:2 http://mirrors.aliyun.com/ubuntu bionic-security InRelease
>   Temporary failure resolving 'mirrors.aliyun.com'
> Err:3 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease
>   Temporary failure resolving 'mirrors.aliyun.com'
> Err:4 http://mirrors.aliyun.com/ubuntu bionic-proposed InRelease
>   Temporary failure resolving 'mirrors.aliyun.com'
> Err:5 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease
>   Temporary failure resolving 'mirrors.aliyun.com'
> Reading package lists...
> W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
> W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
> W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
> W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-proposed/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
> W: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'mirrors.aliyun.com'
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> Removing intermediate container 1e5da74dd0cd
>  ---> 52c618edfb13
> Step 9/17 : RUN apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y
>  ---> Running in c9aa9920a38f
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package locales is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Unable to locate package wget
> E: Unable to locate package git
> E: Package 'locales' has no installation candidate
> E: Unable to locate package ttf-wqy-zenhei
> E: Unable to locate package sudo
> E: Unable to locate package tzdata
> The command '/bin/sh -c apt-get install wget git locales ttf-wqy-zenhei sudo tzdata -y' returned a non-zero code: 100
> build docker image error,exit process
> ```

Replace the available ubuntu sources
