### ISSUE TITLE
阿里源似乎不再更新

### ISSUE THREAD

**Issue by Sciroccogti** [RokasUrbelis/docker-wine-linux#53]
[阿里源](http://mirrors.aliyun.com/deepin/pool/non-free/d/) 好像没有什么软件了，不如直接从 [deepin 源](http://packages.deepin.com/deepin/pool/non-free/d/) 下载

**Comment by RokasUrbelis** [comment]
> [阿里源](http://mirrors.aliyun.com/deepin/pool/non-free/d/) 好像没有什么软件了，不如直接从 [deepin 源](http://packages.deepin.com/deepin/pool/non-free/d/) 下载

已采纳，感谢建议
