### ISSUE TITLE
BaiduNetDisk 弹出认证

### ISSUE THREAD

**Issue by hellodword** [RokasUrbelis/docker-wine-linux#8]
我的账号初次登录会弹出百度认证...然后就一直卡在白屏了...请问应该怎么解决呢? 感谢

![docker baidu](https://user-images.githubusercontent.com/46193371/56406139-82c9d480-62a2-11e9-8715-b6e9d95c793b.png)

**Comment by hellodword** [comment]
Ubuntu 18.04.2 LTS

**Comment by RokasUrbelis** [comment]
> 我的账号初次登录会弹出百度认证...然后就一直卡在白屏了...请问应该怎么解决呢? 感谢
> 
> ![docker baidu](https://user-images.githubusercontent.com/46193371/56406139-82c9d480-62a2-11e9-8715-b6e9d95c793b.png)

如果账号是刚注册的或很久没有登录，尽量不要使用此客户端来验证，因为wine容器崩溃概率很高，其次和你的硬件配置有关，你可以通过
```shell
bash run.sh
sourt start.sh -i xxx baidunetdisk
```
来重新运行试试

**Comment by hellodword** [comment]
> > 我的账号初次登录会弹出百度认证...然后就一直卡在白屏了...请问应该怎么解决呢? 感谢
> > ![docker baidu](https://user-images.githubusercontent.com/46193371/56406139-82c9d480-62a2-11e9-8715-b6e9d95c793b.png)
> 
> 如果账号是刚注册的或很久没有登录，尽量不要使用此客户端来验证，因为wine容器崩溃概率很高，其次和你的硬件配置有关，你可以通过
> 
> ```shell
> bash run.sh
> sourt start.sh -i xxx baidunetdisk
> ```
> 
> 来重新运行试试

用浏览器认证登录后成功了, 第一次登录的时候保存账号密码自动登录, 进去会黑屏, 但是退出然后再打开就正常了.
